- hosts: all
  roles:
    - common

- hosts: controller
  roles:
    - k3s-controller

- hosts: nodes
  roles:
    - k3s-node
  vars:
    controller_ip: "{{ hostvars[groups['controller'][0]]['ansible_default_ipv4']['address'] }}"
    token: "{{ hostvars[groups['controller'][0]]['token'] }}"
